import assert from 'assert'
import LoginPage from '../pages/login.page'
import HeaderPage from '../pages/header.page'
import { PASSWORD, USER_NAME } from '../utils/env'

describe('Header Test suite',()=>{

    it('Should redirect to new site', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await browser.saveScreenshot('screenShots/heroRosterHome.png')
        await HeaderPage.linkLink.click()
        assert.strictEqual(await browser.getUrl(),'https://glitchitsystem.com/')
        await browser.saveScreenshot('screenShots/newSite.png')
    })

    it('Should open wolverine modal', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await browser.saveScreenshot('screenShots/heroRosterHome.png')
        await HeaderPage.heroFactsLink.click()
        await HeaderPage.wolverineOption.click()
        await browser.pause(1000)
        assert.strictEqual(await HeaderPage.wolverineModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(await HeaderPage.wolverineModalTitleText.getText(),'Wolverine Fact','Title is not the same')
        assert.strictEqual(await HeaderPage.wolverineModalContentText.getText(),'Wolverine made his first comic book appearance in 1974.','Content is not the same')
        await browser.saveScreenshot('screenShots/wolverineModal.png')
        await browser.pause(3000)
    })
    it('Should close wolverine modal', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await browser.saveScreenshot('screenShots/heroRosterHome.png')
        await HeaderPage.heroFactsLink.click()
        await HeaderPage.wolverineOption.click()
        await browser.pause(1000)
        assert.strictEqual(await HeaderPage.wolverineModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(await HeaderPage.wolverineModalTitleText.getText(),'Wolverine Fact','Title is not the same')
        assert.strictEqual(await HeaderPage.wolverineModalContentText.getText(),'Wolverine made his first comic book appearance in 1974.','Content is not the same')
        await browser.saveScreenshot('screenShots/wolverineModal.png')
        await browser.pause(3000)
        await HeaderPage.wolverineModalCloseButton.click()
        await browser.pause(3000)
        assert.strictEqual(await HeaderPage.wolverineModalWindow.isDisplayed(),false,'Modal is still displayed')
        await browser.saveScreenshot('screenShots/wolverineModalClosed.png')
    })

    it('Should open spiderman modal', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await browser.saveScreenshot('screenShots/heroRosterHome.png')
        await HeaderPage.heroFactsLink.click()
        await HeaderPage.spidermanOption.click()
        await browser.pause(1000)
        assert.strictEqual(await HeaderPage.spidermanModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(await HeaderPage.spidermanModalTitleText.getText(),'Spider-Man Fact','Title is not the same')
        assert.strictEqual(await HeaderPage.spidermanModalContentText.getText(),'Spider-man was created by Stan Lee and Steve Ditko and first appeared in 1962.','Content is not the same')
        await browser.saveScreenshot('screenShots/spidermanModal.png')
        await browser.pause(3000)
    })
    it('Should close spiderman modal', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await browser.saveScreenshot('screenShots/heroRosterHome.png')
        await HeaderPage.heroFactsLink.click()
        await HeaderPage.spidermanOption.click()
        await browser.pause(1000)
        assert.strictEqual(await HeaderPage.spidermanModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(await HeaderPage.spidermanModalTitleText.getText(),'Spider-Man Fact','Title is not the same')
        assert.strictEqual(await HeaderPage.spidermanModalContentText.getText(),'Spider-man was created by Stan Lee and Steve Ditko and first appeared in 1962.','Content is not the same')
        await browser.saveScreenshot('screenShots/spidermanModal.png')
        await HeaderPage.spidermanModalCloseButton.click()
        await browser.pause(3000)
        assert.strictEqual(await HeaderPage.spidermanModalWindow.isDisplayed(),false,'Modal is still displayed')
        await browser.saveScreenshot('screenShots/spidermanModalClose.png')
    })
    it('Should search for wolverine', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await browser.saveScreenshot('screenShots/heroRosterHome.png')
        await HeaderPage.searchField.setValue('wolverine')
        await HeaderPage.searchButton.click()
        await browser.pause(3000)
        await browser.saveScreenshot('screenShots/searchResult.png')
    })
    it('Should show error if wolverine is not entered', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await HeaderPage.searchField.setValue('something')
        await HeaderPage.searchButton.click()
        await browser.pause(3000)

    })
    it('Should close the alert', async ()=>{
        await browser.url('')
        await LoginPage.emailField.setValue(USER_NAME)
        await LoginPage.passwordField.setValue(PASSWORD)
        await LoginPage.submitButton.click()
        await HeaderPage.searchField.setValue('something')
        await HeaderPage.searchButton.click()
        await browser.pause(3000)

    })
})
