const assert = require('assert')
const HeaderPage = require('../pages/header.page')
const LoginPage = require('../pages/login.page')

describe('Header Test suite',()=>{
    
    it('Should redirect to new site',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/heroRosterHome.png')
        HeaderPage.linkLink.click()
        assert.strictEqual(browser.getUrl(),'https://glitchitsystem.com/')
        browser.saveScreenshot('screenShots/newSite.png')
    })

    it('Should open wolverine modal',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/heroRosterHome.png')
        HeaderPage.heroFactsLink.click()
        HeaderPage.wolverineOption.click()
        browser.pause(1000)
        assert.strictEqual(HeaderPage.wolverineModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(HeaderPage.wolverineModalTitleText.getText(),'Wolverine Fact','Title is not the same')
        assert.strictEqual(HeaderPage.wolverineModalContentText.getText(),'Wolverine made his first comic book appearance in 1974.','Content is not the same')
        browser.saveScreenshot('screenShots/wolverineModal.png')
        browser.pause(3000)
    })
    it('Should close wolverine modal',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/heroRosterHome.png')
        HeaderPage.heroFactsLink.click()
        HeaderPage.wolverineOption.click()
        browser.pause(1000)
        assert.strictEqual(HeaderPage.wolverineModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(HeaderPage.wolverineModalTitleText.getText(),'Wolverine Fact','Title is not the same')
        assert.strictEqual(HeaderPage.wolverineModalContentText.getText(),'Wolverine made his first comic book appearance in 1974.','Content is not the same')
        browser.saveScreenshot('screenShots/wolverineModal.png')
        browser.pause(3000)
        HeaderPage.wolverineModalCloseButton.click()
        browser.pause(3000)
        assert.strictEqual(HeaderPage.wolverineModalWindow.isDisplayed(),false,'Modal is still displayed')
        browser.saveScreenshot('screenShots/wolverineModalClosed.png')    
    })

    it('Should open spiderman modal',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/heroRosterHome.png')
        HeaderPage.heroFactsLink.click()
        HeaderPage.spidermanOption.click()
        browser.pause(1000)
        assert.strictEqual(HeaderPage.spidermanModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(HeaderPage.spidermanModalTitleText.getText(),'Spider-Man Fact','Title is not the same')
        assert.strictEqual(HeaderPage.spidermanModalContentText.getText(),'Spider-man was created by Stan Lee and Steve Ditko and first appeared in 1962.','Content is not the same')
        browser.saveScreenshot('screenShots/spidermanModal.png')
        browser.pause(3000)
    })
    it('Should close spiderman modal',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/heroRosterHome.png')
        HeaderPage.heroFactsLink.click()
        HeaderPage.spidermanOption.click()
        browser.pause(1000)
        assert.strictEqual(HeaderPage.spidermanModalWindow.isDisplayed(),true,'Modal is not displayed')
        assert.strictEqual(HeaderPage.spidermanModalTitleText.getText(),'Spider-Man Fact','Title is not the same')
        assert.strictEqual(HeaderPage.spidermanModalContentText.getText(),'Spider-man was created by Stan Lee and Steve Ditko and first appeared in 1962.','Content is not the same')
        browser.saveScreenshot('screenShots/spidermanModal.png')
        HeaderPage.spidermanModalCloseButton.click()
        browser.pause(3000)
        assert.strictEqual(HeaderPage.spidermanModalWindow.isDisplayed(),false,'Modal is still displayed')
        browser.saveScreenshot('screenShots/spidermanModalClose.png')
    }) 
    it('Should search for wolverine', ()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/heroRosterHome.png') 
        HeaderPage.searchField.setValue('wolverine')
        HeaderPage.searchButton.click()
        assert.strictEqual(browser.isAlertOpen(),true,'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Wolverine is awesome!','Text is not the same')
        browser.pause(3000)
        browser.saveScreenshot('screenShots/searchResult.png')
    }) 
    it('Should show error if wolverine is not entered',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        HeaderPage.searchField.setValue('something')
        HeaderPage.searchButton.click()
        browser.pause(3000)
        assert.strictEqual(browser.isAlertOpen(),true,'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Your search for something returned 0 reults. Try something else.','Text is not the same')

    }) 
    it('Should close the alert',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        HeaderPage.searchField.setValue('something')
        HeaderPage.searchButton.click()
        browser.pause(3000)
        assert.strictEqual(browser.isAlertOpen(),true,'Alert is not open')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false,'Alert is still open')
        browser.pause(3000)
        
    }) 
})