const assert = require('assert')
const LoginPage = require('../pages/login.page')
const HeaderPage = require('../pages/header.page')
describe('Test suite',()=>{
    //valid email 1@2.com
    //valid password password
    it('Should display error when password is missing',()=>{
        browser.url('')
        LoginPage.emailField.setValue('test@test.com')
        LoginPage.submitButton.click()
        assert.strictEqual(browser.isAlertOpen(),true, 'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Please enter an email and password','Alert text is not same')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false, 'Alert is still open') 
        browser.saveScreenshot('screenShots/screenshot1.png')
    })

    it('Should display error when email is missing',()=>{
        browser.url('')
        LoginPage.passwordField.setValue('test')
        LoginPage.submitButton.click()
        assert.strictEqual(browser.isAlertOpen(),true, 'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Please enter an email and password','Alert text is not same')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false, 'Alert is still open')
        browser.saveScreenshot('screenShots/screenshot2.png')
    })

    it('Should display error when email and password are missing',()=>{
        browser.url('')
        LoginPage.submitButton.click()
        assert.strictEqual(browser.isAlertOpen(),true, 'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Please enter an email and password','Alert text is not same')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false, 'Alert is still open')
        browser.saveScreenshot('screenShots/screenshot3.png')
    })

    it('Should display error when email is incorrect',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1234')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        assert.strictEqual(browser.isAlertOpen(),true, 'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Invalid email and password','Alert text is not same')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false, 'Alert is still open')
        browser.saveScreenshot('screenShots/screenshot4.png')
    })

    it('Should display error when password is incorrect',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password1')
        LoginPage.submitButton.click()
        assert.strictEqual(browser.isAlertOpen(),true, 'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Invalid email and password','Alert text is not same')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false, 'Alert is still open')
        browser.saveScreenshot('screenShots/screenshot5.png')
    })

    it('Should display error when password case is incorrect',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('PASSWORD')
        LoginPage.submitButton.click()
        assert.strictEqual(browser.isAlertOpen(),true, 'Alert is not open')
        assert.strictEqual(browser.getAlertText(),'Invalid email and password', 'Alert text is not same')
        browser.acceptAlert()
        assert.strictEqual(browser.isAlertOpen(),false, 'Alert is still open')
        browser.saveScreenshot('screenShots/screenshot6.png')
    })

    it('Should login with valid email and password',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        assert.strictEqual(LoginPage.loginOverlay.isDisplayed(),false, 'Overlay is still displayed')
        assert.strictEqual(LoginPage.superheroRoster.isDisplayed(),true, 'Superhero Roster Text is still displayed')
        browser.saveScreenshot('screenShots/screenshot7.png')
    })

    it('Should remember login credendtials',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.rememberLoginCheckbox.click()
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/loginSuccess.png')
        assert.strictEqual(LoginPage.loginOverlay.isDisplayed(),false,'Overlay is still displayed')
        HeaderPage.logoutLink.click()
        browser.saveScreenshot('screenShots/logoutSuccess.png')
        assert.strictEqual(LoginPage.loginOverlay.isDisplayed(),true,'Overlay is not displayed')
        assert.strictEqual(LoginPage.emailField.getValue(),'1@2.com', 'Values do not match')
        assert.strictEqual(LoginPage.passwordField.getValue().length, 8,'Password is too short')
        assert.strictEqual(LoginPage.rememberLoginCheckbox.isSelected(),true,'Checkbox is not selected')
    })
    it('should not remember login credentials',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.saveScreenshot('screenShots/home.png')
        browser.pause(3000)
        assert.strictEqual(LoginPage.loginOverlay.isDisplayed(),false,'Overlay is still displayed')
        HeaderPage.logoutLink.click()
        browser.pause(3000)
        assert.strictEqual(LoginPage.loginOverlay.isDisplayed(),true,'overlay is not displayed')
        assert.strictEqual(LoginPage.emailField.getValue(),'','Values do not match')
        assert.strictEqual(LoginPage.passwordField.getValue().length,0,'Length is not same')
        assert.strictEqual(LoginPage.rememberLoginCheckbox.isSelected(),false,'Checkbox is selected')
        //browser.saveScreenshot('screenShots/login.png')
		browser.saveDocumentScreenshot('screenShots/login.png')
    })

})