const assert = require('assert')
const HeaderPage = require('../pages/header.page')
const LoginPage = require('../pages/login.page')
const IntroPage = require('../pages/intro.page')
const RosterPage = require('../pages/roster.page')
const VotePage = require('../pages/vote.page')
describe('Test suite',()=>{
    it('Should smoke test loginpage',()=>{
        browser.url('')
        assert.strictEqual(LoginPage.headingText.isDisplayed(),true,'LoginPage.headingText')
        assert.strictEqual(LoginPage.emailLabel.isDisplayed(),true,'LoginPage.emailLabel')
        assert.strictEqual(LoginPage.emailField.isDisplayed(),true,'LoginPage.emailField')
        assert.strictEqual(LoginPage.passwordLabel.isDisplayed(),true,'LoginPage.passwordLabel')
        assert.strictEqual(LoginPage.passwordField.isDisplayed(),true,'LoginPage.passwordField')
        assert.strictEqual(LoginPage.rememberLoginCheckbox.isDisplayed(),true,'LoginPage.rememberLoginCheckbox')
        assert.strictEqual(LoginPage.rememberLoginLabel.isDisplayed(),true,'LoginPage.rememberLoginLabel')
        assert.strictEqual(LoginPage.submitButton.isDisplayed(),true,'LoginPage.submitButton')
        browser.pause(5000)
    })

    it('Should smoke test headerpage',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        browser.pause(3000)
        assert.strictEqual(HeaderPage.logoutLink.isDisplayed(),true,'HeaderPage.logoutLink')
        assert.strictEqual(HeaderPage.linkLink.isDisplayed(),true,'HeaderPage.linkLink')
        assert.strictEqual(HeaderPage.heroFactsLink.isDisplayed(),true,'HeaderPage.heroFactsLink')
        HeaderPage.heroFactsLink.click()
        browser.pause(3000)
        assert.strictEqual(HeaderPage.wolverineOption.isDisplayed(),true,'HeaderPage.wolverineOption')
        assert.strictEqual(HeaderPage.spidermanOption.isDisplayed(),true,'HeaderPage.spidermanOption')
        assert.strictEqual(HeaderPage.searchField.isDisplayed(),true,'HeaderPage.searchField')
        assert.strictEqual(HeaderPage.searchButton.isDisplayed(),true,'HeaderPage.searchButton')
        //assert.strictEqual(HeaderPage.searchField.isDisplayed(),true,'HeaderPage.searchField')
        browser.pause(3000)

    })

    it('Should smoke test intropage',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        
        assert.strictEqual(IntroPage.titleText.isDisplayed(),true,'IntroPage.titleText')
        assert.strictEqual(IntroPage.mainImage.isDisplayed(),true,'IntroPage.mainImage')
        browser.pause(3000)

    })

    it('Should smoke test rosterpage',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        
        assert.strictEqual(RosterPage.instructionText.isDisplayed(),true,'RosterPage.instructionText')
        assert.strictEqual(RosterPage.listTitle.isDisplayed(),true,'RosterPage.listTitle')
        assert.strictEqual(RosterPage.wolverineItem.isDisplayed(),true,'RosterPage.wolverineItem')
        assert.strictEqual(RosterPage.ironManItem.isDisplayed(),true,'RosterPage.ironManItem')
        assert.strictEqual(RosterPage.deadpoolItem.isDisplayed(),true,'RosterPage.deadpoolItem')
        assert.strictEqual(RosterPage.thorItem.isDisplayed(),true,'RosterPage.thorItem')
        assert.strictEqual(RosterPage.spidermanItem.isDisplayed(),true,'RosterPage.spidermanItem')
        assert.strictEqual(RosterPage.addHeroLabel.isDisplayed(),true,'RosterPage.addHeroLabel')
        assert.strictEqual(RosterPage.addHeroField.isDisplayed(),true,'RosterPage.addHeroField')
        assert.strictEqual(RosterPage.submitButton.isDisplayed(),true,'RosterPage.submitButton')
        browser.pause(7000)

    })

    it('Should smoke test votepage',()=>{
        browser.url('')
        LoginPage.emailField.setValue('1@2.com')
        LoginPage.passwordField.setValue('password')
        LoginPage.submitButton.click()
        
        assert.strictEqual(VotePage.voteTitle.isDisplayed(),true,'VotePage.voteTitle')
        assert.strictEqual(VotePage.voteItem1.isDisplayed(),true,'VotePage.voteItem1')
        assert.strictEqual(VotePage.voteItem2.isDisplayed(),true,'VotePage.voteItem2')
        assert.strictEqual(VotePage.voteItem3.isDisplayed(),true,'VotePage.voteItem3')
        assert.strictEqual(VotePage.voteItem4.isDisplayed(),true,'VotePage.voteItem4')
        assert.strictEqual(VotePage.voteItem5.isDisplayed(),true,'VotePage.voteItem5')
        assert.strictEqual(VotePage.voteItemLabel1.isDisplayed(),true,'VotePage.voteItemLabel1')
        assert.strictEqual(VotePage.voteItemLabel2.isDisplayed(),true,'VotePage.voteItemLabel2')
        assert.strictEqual(VotePage.voteItemLabel3.isDisplayed(),true,'VotePage.voteItemLabel3')
        assert.strictEqual(VotePage.voteItemLabel4.isDisplayed(),true,'VotePage.voteItemLabel4')
        assert.strictEqual(VotePage.voteItemLabel5.isDisplayed(),true,'VotePage.voteItemLabel5')
        assert.strictEqual(VotePage.submitButton.isDisplayed(),true,'VotePage.submitButton')
        assert.strictEqual(VotePage.voteItemText1.isDisplayed(),true,'VotePage.voteItemText1')
        assert.strictEqual(VotePage.voteItemValue1.isDisplayed(),true,'VotePage.voteItemValue1')
        assert.strictEqual(VotePage.voteItemText2.isDisplayed(),true,'VotePage.voteItemText2')
        assert.strictEqual(VotePage.voteItemValue2.isDisplayed(),true,'VotePage.voteItemValue2')
        assert.strictEqual(VotePage.voteItemText3.isDisplayed(),true,'VotePage.voteItemText3')
        assert.strictEqual(VotePage.voteItemValue3.isDisplayed(),true,'VotePage.voteItemValue3')
        assert.strictEqual(VotePage.voteItemText4.isDisplayed(),true,'VotePage.voteItemText4')
        assert.strictEqual(VotePage.voteItemValue4.isDisplayed(),true,'VotePage.voteItemValue4')
        assert.strictEqual(VotePage.voteItemText5.isDisplayed(),true,'VotePage.voteItemText5')
        assert.strictEqual(VotePage.voteItemValue5.isDisplayed(),true,'VotePage.voteItemValue5')
        browser.pause(10000)
        

    })
})